---
- name: "Download Kibana deb"
  get_url:
    url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ kibana_version }}-amd64.deb"
    dest: "files/kibana-{{ kibana_version }}-amd64.deb"
  register: download_kibana
  delegate_to: localhost
  until: download_kibana is succeeded
  when: elastic_install_type == 'remote'
- name: Copy kibana to managed node
  copy:
    src: "files/kibana-{{ kibana_version }}-amd64.deb"
    mode: 0644
    dest: "/tmp/kibana-{{ kibana_version }}-amd64.deb"
