---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos7
    image: milcom/centos7-systemd
    pre_build_image: true
    privileged: true
  - name: ubuntu
    image: jrei/systemd-ubuntu
    pre_build_image: true
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/usr/sbin/init"
provisioner:
  name: ansible
verifier:
  name: ansible
